config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'search', to: 'search#search'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    searchkick word_start: [:name]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    #@books = Book.all
    @books = Book.page(params[:page]).per(10)
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :price, :description, :author, :year, :ratings, :genre)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search
        
        args ={}
        args[:ratings] = params[:ratings] if params[:ratings].present?
        args[:author] = params[:author] if params[:author].present?
        args[:year] = params[:year] if params[:year].present?
        args[:genre] = params[:genre] if params[:genre].present?
        #price_ranges = [{to: 200}, {from: 200, to: 400}, {from: 400, to: 600}, {from: 600}]
        price_ranges = [{from: 0, to: 20}, {from: 20, to: 50}, {from: 50}]
        
        @results = Book.search(params[:search], page: params[:page], per_page: 5, where: args, aggs: {price: {ranges: price_ranges}, ratings:{}, author:{}, year:{}, genre:{}})
        
        @ratings_aggregations = @results.aggs['ratings']
        @author_aggregations = @results.aggs['author']
        @year_aggregations = @results.aggs['year']
        @genre_aggregations = @results.aggs['genre']
        @price_aggregations = @results.aggs['price']
        
        @results = Book.search('*', page: params[:page], per_page: 5) if params[:search].blank?
        
        if params[:sort_by] == 'price_high_to_low'
            @results = @results.order(price: :desc)
            #@results = @results.where(year: params[:sort_by]).order(price: :desc) if params[:sort_by_year].blank?
        elsif params[:sort_by] == 'price_low_to_high'
            @results = @results.order(price: :asc)
        elsif params[:sort_by_year].present?
            @results = @results.where(year: params[:sort_by_year])
        elsif params[:selected_genre].present?
            @results = @results.where(genre: params[:selected_genre])
        end
        
        render turbo_stream:
            turbo_stream.update('books', partial: 'books/books', locals: { books: @results })
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Price: ₹</strong>
    <%= book.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>
  
  <p>
    <strong>Genre:</strong>
    <%= book.genre %>
  </p>
  
  <p>
    <strong>Year:</strong>
    <%= book.year %>
  </p>
  
  <p>
    <strong>Rating:</strong>
    <%= book.ratings %>
  </p>

</div>

app/views/books/_books.html.erb
<div class="col-12">
        <%= turbo_frame_tag 'search-form' do %>
          <%= form_with url: search_path, method: :get, id: 'search-form', class: 'mb-3' do |form| %>
            <div class="input-group">
              <%= form.label :search, "Search for:", class: 'input-group-text' %>
              <%= form.text_field :search, class: 'form-control' %>
              <!--<= form.select :sort_by_year, options_for_select((1990..Date.today.year), params[:year]), include_blank: true, class: 'form-select', data: { action: 'change->filter-by-year#filterByYear' } %>-->
              <%= form.submit "Search", class: 'btn btn-primary' %>
            </div>
          <% end %>
        <% end %>
</div>

<div class="filters" data-controller="sort-by">
          <h4>Sort By:</h4>
          <ul class="list-unstyled">
            <li>
              <%= link_to 'Price (High to Low)', search_path(sort_by: 'price_high_to_low'), class: 'btn btn-link', data: { action: 'click->sort-by#sortBy' } %>
            </li>
            <li>
              <%= link_to 'Price (Low to High)', search_path(sort_by: 'price_low_to_high'), class: 'btn btn-link', data: { action: 'click->sort-by#sortBy' } %>
            </li>
          </ul>
        </div>

<% if @rating_aggregations.present? %>    
<div class="row">
  <div class="col-12">
    <div class="filters" data-controller="filter-by-rating">
      <h4>Filter By Rating:</h4>
      <% @rating_aggregations['buckets'].each do |bucket| %>
        <%= link_to "Ratings: #{bucket['key']} (Count: #{bucket['doc_count']})", request.params.merge(rating: bucket["key"]) %>
        <!--<= link_to bucket['key'], search_path(selected_genre: bucket['key']), class: 'btn btn-link', data: { action: 'click->filter-by-genre#filterByGenre' } %>-->
      <% end %>
    </div>
  </div>
</div>    
<% end %>

<% if @author_aggregations.present? %>    
<div class="row">
  <div class="col-12">
    <div class="filters" data-controller="filter-by-author">
      <h4>Filter By Author:</h4>
      <% @author_aggregations['buckets'].each do |bucket| %>
        <%= link_to "Author: #{bucket['key']} (Count: #{bucket['doc_count']})", request.params.merge(author: bucket["key"]) %>
        <!--<= link_to bucket['key'], search_path(selected_genre: bucket['key']), class: 'btn btn-link', data: { action: 'click->filter-by-genre#filterByGenre' } %>-->
      <% end %>
    </div>
  </div>
</div>    
<% end %>

<% if @genre_aggregations.present? %>    
<div class="row">
  <div class="col-12">
    <div class="filters" data-controller="filter-by-genre">
      <h4>Filter By Genre:</h4>
      <% @genre_aggregations['buckets'].each do |bucket| %>
        <%= link_to "Genre: #{bucket['key']} (Count: #{bucket['doc_count']})", request.params.merge(genre: bucket["key"]) %>
        <!--<= link_to bucket['key'], search_path(selected_genre: bucket['key']), class: 'btn btn-link', data: { action: 'click->filter-by-genre#filterByGenre' } %>-->
      <% end %>
    </div>
  </div>
</div>    
<% end %>

<% if @year_aggregations.present? %>    
<div class="row">
  <div class="col-12">
    <div class="filters" data-controller="filter-by-year">
      <h4>Filter By Year:</h4>
      <% @year_aggregations['buckets'].each do |bucket| %>
        <%= link_to "Year: #{bucket['key']} (Count: #{bucket['doc_count']})", request.params.merge(year: bucket["key"]) %>
        <!--<= link_to bucket['key'], search_path(selected_genre: bucket['key']), class: 'btn btn-link', data: { action: 'click->filter-by-genre#filterByGenre' } %>-->
      <% end %>
    </div>
  </div>
</div>    
<% end %>

<% if @price_aggregations.present? %>
  <h3>Price Ranges</h3>
  <% @price_aggregations['buckets'].each do |bucket| %>
    <p>
      <%= link_to "#{bucket['key']} (Count: #{bucket['doc_count']})", request.params.merge(price_range: bucket['key']) %>
    </p>
  <% end %>
<% end %>


<% books.each do |book| %>
  <div class="card mb-3" style= "margin-top: 2%">
    <div class="card-body">
      <%= render book %>
      <p>
        <%= link_to "Show this book", book, class: "btn btn-primary" %>
      </p>
    </div>
  </div>
<% end %>

<div class="d-flex justify-content-center">
  <%= paginate books %>
</div>
  <!--added pagination in this books partial to paginate the search results-->

app/views/books/_form.html.erb
<%= turbo_frame_tag 'search-results' do %>
  <%= form_with(model: book) do |form| %>
    <% if book.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
  
        <ul>
          <% book.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.number_field :price %>
    </div>
  
    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description %>
    </div>
  
    <div>
      <%= form.label :author, style: "display: block" %>
      <%= form.text_field :author %>
    </div>
  
    <div>
      <%= form.label :genre, style: "display: block" %>
      <%= form.text_field :genre %>
    </div>
  
    <div>
      <%= form.label :year, style: "display: block" %>
      <%= form.number_field :year %>
    </div>
    
    <div>
      <%= form.label :ratings, style: "display: block" %>
      <%= form.number_field :ratings %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/books/edit.html.erb
<%= turbo_frame_tag 'search-results' do %>
  <h1>Editing book</h1>
  
  <%= render "form", book: @book %>
  
  <br>
  
  <div>
    <%= link_to "Show this book", @book %> |
    <%= link_to "Back to books", books_path %>
  </div>
<% end %>

app/views/books/index.html.erb
    <!--<div class="row">-->
    <!--  <div class="col-12">-->
    <!--    <div class="filters" data-controller="filter-by-year">-->
    <!--      <h4>Filter By Year:</h4>-->
    <!--      <= form_with url: search_path, method: :get, id: 'filter-form' do |form| %>-->
    <!--        <div class="input-group">-->
    <!--          <= form.select :sort_by_year, options_for_select((1990..Date.today.year), params[:year]), include_blank: true, class: 'form-select', data: { action: 'change->filter-by-year#filterByYear' } %>-->
    <!--          <= form.submit "Apply Filter", class: 'btn btn-primary' %>-->
    <!--        </div>-->
    <!--      < end %>-->
    <!--    </div>-->
    <!--  </div>-->
    <!--</div>-->
    
<%= turbo_frame_tag 'search-results' do %>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p class="text-success"><%= notice %></p>
        <h1>Books</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <div id="books" data-controller="load-more">
          <%= render 'books/books', books: @books %>
        </div>
      </div>
    </div>
    
    <!--<div id="books">-->
    <!--  <= render 'books/books', books: @books %>-->
    <!--</div>-->


    <div class="row">
      <div class="col-12">
        <%= link_to "New book", new_book_path, class: 'btn btn-success mt-3' %>
      </div>
    </div>
  </div>
<% end %>

app/views/books/new.html.erb
<%= turbo_frame_tag 'search-results' do %>
    <h1>New book</h1>
    
    <%= render "form", book: @book %>
    
    <br>
    
    <div>
      <%= link_to "Back to books", books_path %>
    </div>
<% end %>

app/views/books/show.html.erb
<%= turbo_frame_tag 'search-results' do %>
  <p style="color: green"><%= notice %></p>
  
  <%= render @book %>
  
  <div>
    <%= link_to "Edit this book", edit_book_path(@book) %> |
    <%= link_to "Back to books", books_path %>
  
    <%= button_to "Destroy this book", @book, method: :delete %>
  </div>
<% end %>

app/views/home/index.html.erb
<style>
    /* Reset some default styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

/* Global styles */
body {
  font-family: Arial, sans-serif;
}

header {
  background-color: #333;
  color: #fff;
  padding: 20px;
  display: flex;
  justify-content: space-between;
}

.logo h1 {
  font-size: 24px;
}

nav ul {
  list-style: none;
}

nav ul li {
  display: inline-block;
  margin-right: 10px;
}

nav ul li a {
  color: #fff;
  text-decoration: none;
}

section.hero {
  background-color: #f2f2f2;
  padding: 50px;
  text-align: center;
}

section.hero h1 {
  font-size: 36px;
  margin-bottom: 20px;
}

section.hero p {
  font-size: 18px;
  color: #666;
  margin-bottom: 30px;
}

a.btn {
  display: inline-block;
  background-color: #333;
  color: #fff;
  padding: 10px 20px;
  text-decoration: none;
  border-radius: 4px;
  transition: background-color 0.3s;
}

a.btn:hover {
  background-color: #555;
}

section.features {
  display: flex;
  justify-content: space-between;
  padding: 50px;
}

.feature {
  flex-basis: 30%;
  background-color: #fff;
  padding: 20px;
  text-align: center;
  border-radius: 4px;
  box-shadow: 0 2px 4px rgba(0

</style>

  <header>
    <div class="logo">
      <h1>Elasticsearch</h1>
    </div>
    <nav>
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </nav>
  </header>
  
  <section class="hero">
    <div class="hero-content">
      <h1>Welcome to My Awesome Website</h1>
      <p>Discover the best products and services that cater to your needs.</p>
      <a href="#" class="btn">Get Started</a>
    </div>
  </section>
  
  <section class="features">
    <div class="feature">
      <h2>Feature 1</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </div>
    <div class="feature">
      <h2>Feature 2</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </div>
    <div class="feature">
      <h2>Feature 3</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </div>
  </section>
  
  <footer>
    <p>&copy; 2023 My Awesome Website. All rights reserved.</p>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elasticsearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>